name: RegionalTextures
version: 1.0.0-RELEASE
main: com.shiniofthegami.regionaltextures.RegionalTextures
author: [ShiniOfTheGami]
depend: [WorldGuard]

commands:
  packs:
    permission: regionaltextures.manage.packs
    description: manage packs
    usage: |
      USAGE:
      /packs list - Lists all current packs
      /packs add <name> <url> - adds a pack
      /packs remove <name> - removes a pack
  overlays:
    permission: regionaltextures.manage.overlays
    description: manage overlays
    usage: |
      USAGE:
      /overlays list - Lists all current overlays
      /overlays add <name> <region> <pack> - adds an overlay
      /overlays remove <name> - removes an overlay
      /overlays update - updates the overlays to use changed pack URLs
  toggletextures:
    description: Toggles whether or not the regional textures get applied to you
    usage: /<command>
  usepack:
    description: Sets resourcepack for you
    usage: |
      USAGE:
      /usepack automatic - Changes resource pack to the pack at your location (turns automatic changing on)
      /usepack default - Sets resource pack to default pack of the server (turns automatic changing off)
      /usepack <resource pack> - Changes resource pack to the pack spesified (turns automatic changing off)