name: RegionalTextures
version: 1.0.0-RELEASE
main: com.shiniofthegami.regionaltextures.RegionalTextures
author: [ShiniOfTheGami]
depend: [WorldGuard]

commands:
  packs:
    permission: regionaltextures.manage.packs
    description: manage packs
    usage: |
      USAGE:
      /packs list - Lists all current packs
      /packs add <name> <url> - adds a pack
      /packs remove <name> - removes a pack
  overlays:
    permission: regionaltextures.manage.overlays
    description: manage overlays
    usage: |
      USAGE:
      /overlays list - Lists all current overlays
      /overlays add <name> <region> <pack> - adds an overlay
      /overlays remove <name> - removes an overlay
      /overlays update - updates the overlays to use changed pack URLs